import { Paths } from './path.ts';

export const pathsMap = {
    [Paths.R_SWITCHER]: 'Главная',
    vegan: 'Веганская кухня',
    snacks: 'Закуски',
    salads: 'Салаты',
    'meat-salads': 'Мясные салаты',
    'fish-salads': 'Рыбные салаты',
    'vegetables-salads': 'Овощные салаты',
    'warm-salads': 'Теплые салаты',
    'meat-snacks': 'Мясные закуски',
    'fish-snacks': 'Рыбные закуски',
    'vegetables-snacks': 'Овощные закуски',
    'warm-snacks': 'Теплые закуски',
    'warm-sandwiches': 'Бутерброды',
    'fast-food': 'Фастфуд',
    'meat-soups': 'Мясные супы',
    'vegetables-soups': 'Овощные супы',
    bouillons: 'Бульоны',
    'cold-soups': 'Холодные супы',
    'warm-soups': 'Диетические супы',
    meat: 'Мясные',
    fish: 'Рыбные',
    vegetables: 'Овощные',
    'poultry-dish': 'Из птицы',
    'mushroom-dish': 'Из грибов',
    'offal-dish': 'Из субпродуктов',
    'steamed-soups': 'На пару',
    dumplings: 'Пельмени, вареники',
    'flour-side-dishes': 'Мучные гарниры',
    'vegetable-side-dishes': 'Овощные гарниры',
    pizza: 'Пицца',
    sushi: 'Суши',
    pancakes: 'Блины и оладьи',
    pies: 'Пироги и пончики',
    cakes: 'Торты',
    rolls: 'Рулеты',
    cupcakes: 'Кексы и маффины',
    'cottage-cheese-pancakes': 'Сырники и ватрушки',
    'puff-pastry': 'Из слоеного теста',
    'choux-pastry': 'Из заварного теста',
    'yeast-dough': 'Из дрожжевого теста',
    bun: 'Булочки и сдоба',
    bread: 'Хлеб',
    'pizza-dough': 'Тесто на пиццу',
    creams: 'Кремы',
    'grilled-beef': 'Говядина',
    'grilled-pork': 'Свинина',
    'grilled-poultry': 'Птица',
    'grilled-fish': 'Рыба',
    'grilled-mushrooms': 'Грибы',
    'grilled-vegetables': 'Овощи',
    'first-dish': 'Первые блюда',
    'second-dish': 'Вторые блюда',
    'side-dishes': 'Гарниры',
    desserts: 'Десерты',
    bakery: 'Выпечка',
    'row-food-dishes': 'Сыроедческие блюда',
    drinks: 'Напитки',
    'gluten-dish': 'Без глютена',
    'sugar-dish': 'Без сахара',
    'allergen-dishes': 'Без аллергенов',
    'for-baby': 'Блюда для прикорма',
    'children-diet': 'Детская диета',
    'diet-1': 'Диета №1',
    'diet-2': 'Диета №2',
    'diet-3': 'Диета №3',
    'diet-4': 'Диета №4',
    'diet-5': 'Диета №5',
    'diet-6': 'Диета №6',
    'diet-7': 'Диета №7',
    'diet-8': 'Диета №8',
    'diet-9': 'Диета №9',
    'diet-10': 'Диета №10',
    'diet-11': 'Диета №11',
    'diet-12': 'Диета №12',
    'diet-13': 'Диета №13',
    'gluten-free-diet': 'Без глютена',
    'allergen-free-diet': 'Без аллергенов',
    american: 'Американская кухня',
    armenians: 'Армянская кухня',
    greek: 'Греческая кухня',
    georgian: 'Грузинская кухня',
    italian: 'Итальянская кухня',
    spanish: 'Испанская кухня',
    chinese: 'Китайская кухня',
    mexican: 'Мексиканская кухня',
    'pan-asian': 'Паназиатская кухня',
    russian: 'Русская кухня',
    turkish: 'Турецкая кухня',
    french: 'Французская кухня',
    swedish: 'Шведская кухня',
    japanese: 'Японская кухня',
    different: 'Другая кухня',
    'meat-souses': 'Соусы мясные',
    'cheese-souses': 'Соусы сырные',
    marinades: 'Маринады',
    'meat-zagotovki': 'Мясные заготовки',
    'fish-zagotovki': 'Рыбные заготовки',
    'cucumber-zagotovki': 'Из огурцов',
    'tomato-zagotovki': 'Из томатов',
    'mushroom-zagotovki': 'Из грибов',
    'vegetables-zagotovki': 'Овощные заготовки',
    'salads-zagotovki': 'Салаты, икра',
    'fruit-zagotovki': 'Из фруктов и ягод',
    juices: 'Соки и фреши',
    smoothie: 'Смузи',
    compotes: 'Компоты',
    jelly: 'Кисели',
    coffee: 'Кофе',
    'health-tea': 'Лечебный чай',
    kvass: 'Квас',
    cocktails: 'Коктейли',
    alcohol: 'Алкогольные',
    dessert: 'Десерты и выпечка',
    'grilled-dishes': '',
    'children-dishes': 'Детские блюда',
    'healthy-food': 'Лечебное питание',
    national: 'Национальные',
    souses: 'Соусы',
    zagotovki: 'Домашние заготовки',
};
